name: assignment
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: rootshell <email@example.com>

environment:
  sdk: '>=2.7.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.15.3
